### ISSUE TITLE
Error when redirect after allow

### ISSUE THREAD

**Issue by ElizavetaNevostrueva** [vkolodrevskiy/spring-social-vkontakte#26]
Hello) Can you help me, i try to use your library for sing in with VK. But after click button allow on VK, i get error "Exception while handling OAuth2 callback (null). Redirecting to vkontakte connection status page" if i run my app on ubuntu, or error "java.lang.ClassNotFoundException: org.codehaus.jackson.map.Module". For sing in in my config i use ConnectController. What can I do wrong?

**Comment by vkolodrevskiy** [comment]
What was the problem?
