### ISSUE TITLE
VkontakteProfile misses LastSeen field

### ISSUE THREAD

**Issue by Klaxon77** [vkolodrevskiy/spring-social-vkontakte#31]
There is no way to get LastSeen from VkontakteProfile.

Solution:
Just add field lastSeen of already existing type LastSeen to VkontakteProfile and VkontakteProfileMixin

**Comment by vkolodrevskiy** [comment]
@Klaxon77 closing with https://github.com/vkolodrevskiy/spring-social-vkontakte/pull/32
