### ISSUE TITLE
GroupOperations miss implementation of  groups.getMembers and groups.getById methods

### ISSUE THREAD

**Issue by Klaxon77** [vkolodrevskiy/spring-social-vkontakte#33]
According to VK documentation we can request Groups by their id/screenName:
http://vk.com/dev/groups.getById

Also we are able to get members of any group with the help of method groups.getMembers:
http://vk.com/dev/groups.getMembers

**Comment by vkolodrevskiy** [comment]
spring-social-vkontakte was refactored in 2.0.0 and right now internally uses VK Java SDK(https://vk.com/dev/Java_SDK) as API client implementation. Please refer it to use these methods, how to use new version of spring-social-vkontakte you can check samples under https://github.com/vkolodrevskiy/spring-social-vkontakte/wiki/Sample-usage
