### ISSUE TITLE
Getting Exception java.lang.NoSuchFieldError: ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT

### ISSUE THREAD

**Issue by stephan--** [vkolodrevskiy/spring-social-vkontakte#35]
Hi Viktor,

first of all thank you for investing your time in building this extension.
Im trying to integrate your vk extension (using your latest Snapshot 1.1.0.BUILD-SNAPSHOT from 1st of July) and getting the following Exception after i was being redirected to vk and accepted all requested permissions. After i was running your showcase example app and got the same exception.

As im new to Spring MVC (using 4.1.6 with Java 8) i would call myself a newbe and it might be possible that this is a mistake made by me (switching currently from Grails). If you need further informations please let me know :-)
If this is a Bug: is there a kind of stable version which you would recommend?

``` java
java.lang.NoSuchFieldError: ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT
    org.springframework.social.vkontakte.api.impl.VKontakteTemplate.registerJsonModule(VKontakteTemplate.java:91)
    org.springframework.social.vkontakte.api.impl.VKontakteTemplate.initialize(VKontakteTemplate.java:74)
    org.springframework.social.vkontakte.api.impl.VKontakteTemplate.<init>(VKontakteTemplate.java:70)
    org.springframework.social.vkontakte.connect.VKontakteServiceProvider.getApi(VKontakteServiceProvider.java:36)
    org.springframework.social.vkontakte.connect.VKontakteServiceProvider.getApi(VKontakteServiceProvider.java:26)
    org.springframework.social.connect.support.OAuth2Connection.initApi(OAuth2Connection.java:134)
    org.springframework.social.connect.support.OAuth2Connection.<init>(OAuth2Connection.java:73)
    org.springframework.social.connect.support.OAuth2ConnectionFactory.createConnection(OAuth2ConnectionFactory.java:93)
    org.springframework.social.connect.web.ConnectSupport.completeConnection(ConnectSupport.java:161)
    org.springframework.social.connect.web.ConnectController.oauth2Callback(ConnectController.java:279)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:497)
    org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
    org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
```

**Comment by stephan--** [comment]
Ok found the reason. After updating my jackson-core and jackson-databind libs from 2.4.1 to 2.5.4 everything seems to be fine. Sorry :-)

**Comment by stephan--** [comment]
Not sure if i should reopen but i forgot that using the maven sample project the error still exists of course. In the pmx.xml dependency tree its showing the version 2.3.2 of these two libs is used.

**Comment by vipmax** [comment]
"After updating my jackson-core and jackson-databind libs from 2.4.1 to 2.5.4 everything seems to be fine" Thanks a lot!!!!

<dependency>
            <groupId>org.springframework.social</groupId>
            <artifactId>spring-social-vkontakte</artifactId>
            <version>1.1.0.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.5.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.5.4</version>
        </dependency><dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.5.4</version>
        </dependency>
