### ISSUE TITLE
org.springframework.social.vkontakte.api.impl.VKontakteTemplate javadoc incorrect

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#36]
org.springframework.social.vkontakte.api.impl.VKontakteTemplate advertises the following:

"There are some operations, such as searching, that do not require OAuth
authentication. In those cases, you may use a {@link VKontakteTemplate} that is
created through the default constructor and without any OAuth details."

This is not true since in method initSubApis() the value of isAuthorized() is passed which evaluates to false since accessToken is null. As a result user searches will fail in org.springframework.social.vkontakte.api.impl.UsersTemplate.getUsers(List<Long> userIds, String fields) since it calls requireAuthorization() from org.springframework.social.vkontakte.api.impl.AbstractVKontakteOperations which throws a org.springframework.social.MissingAuthorizationException if isAuthorized is false.

A simple unit test demonstrates this:
//restTemplate and objectMapper are mock objects.
UsersTemplate template = new UsersTemplate(restTemplate, null, objectMapper, false);
template.getUser();

**Comment by vkolodrevskiy** [comment]
spring-social-vkontakte was refactored in 2.0.0 and right now internally uses VK Java SDK(https://vk.com/dev/Java_SDK) as API client implementation. This issue is obsolete now since there's no own API client implementation.
