### ISSUE TITLE
org.springframework.social.vkontakte.api.IUsersOperations does not have method for searching based on user screen name

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#37]
The users.get API method allow for searching for a users based on screen name if the parameter screen_name is specified. Currently the org.springframework.social.vkontakte.api.IUsersOperations only specifies searches based on a user id. Can the org.springframework.social.vkontakte.api.IUsersOperations be expanded to allow to search for screen names?

**Comment by dan-s1** [comment]
This may be a non issue as I am trying to specify screen_name passing in a a screen name and I am getting a 103 error indicating invalid user id.

**Comment by dan-s1** [comment]
It looks like API method utils.resolveScreenName would have to to be called first to get the user id and then users.get.

**Comment by vkolodrevskiy** [comment]
Closing as obsolete.
Refer to VK Java SDK.
