### ISSUE TITLE
org.springframework.social.vkontakte.api.IUserOperations.getUsers throws Exception rendering the call unusable

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#41]
I am trying to call org.springframework.social.vkontakte.api.IUserOperations.getUsers with a user id as a String and I am getting a org.spring.framework.http.converters.HttpMessageNotReadableException
with the message "Could not read Json: Unrecognized field "user_videos" (class org.spring.framework.social.vkontakte.api.counter), not marked as ignorable. 

I suspect the org.springframework.social.vkontakte.api.impl.json.CountersMixin does not define the annotation @JsonIgnoreProperties(ignoreUnknown=true) like many of the other classes do.

**Comment by disovi** [comment]
yes, counters have beend changed a bit since last test data update. You can exclude counters from fields for now.

**Comment by dan-s1** [comment]
I am trying to exclude counters and I am still getting the same problem

**Comment by disovi** [comment]
Can you show your method call?

**Comment by dan-s1** [comment]
Sorry it was my error as I had not made a change to my code to remove it. It is now working fine after counters are removed.
