### ISSUE TITLE
org.springframework.social.vkontakte.api.VKontakteProfile does not have fields for Instagram and livejournal user names

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#42]
Per the Vk documentation (http://vk.com/dev/fields_2) for the connections field there are multiple values possible skype, facebook, twitter, livejournal, instagram. I noticed between the org.springframework.social.vkontakte.api.VKontakteProfile and the org.springframework.social.vkontakte.api.impl.json.VKontakteProfileMixin there are placeholders for 
skype, facebook, facebookName and twitter. Can these classes be modified to allow for storing the instagram and  livejournal user names? Thanks!

**Comment by dan-s1** [comment]
I noticed in commit 850aef3 an instagram property was added to 
org.springframework.social.vkontakte.api.VKontakteProfile.java and to 
org.springframework.social.vkontakte.api.impl.json.VKontakteProfileMixin.java. The problem I noticed is in the resulting JSON there is no instagram field as there is no JsonProperty annotation over the instagram property in org.springframework.social.vkontakte.api.impl.json.VKontakteProfileMixin.java as there is with the other properties (@JsonProperty("instagram") )

**Comment by dan-s1** [comment]
Sorry 850aef3 is the parent and specifically commit 138511428651a0abcd8d870b98d7fd435ee88f70

**Comment by disovi** [comment]
There is no need to annotate fields wich names are identical to json names. Instagram field should work properly, you can check the test https://github.com/vkolodrevskiy/spring-social-vkontakte/blob/master/spring-social-vkontakte/src/test/java/org/springframework/social/vkontakte/api/impl/UsersTemplateTest.java

**Comment by dan-s1** [comment]
I noticed that is was working for other users but I had a case in point where a user had multiple connections, instagram being one of them and it was not showing up.
Also I am curious if there is no need to annotate fields whose names are identical to json names, then why are domain, online, twitter, skype, facebook, site, status, graduation, relation, interests, music, activities, movies, tv, books, games, about and quotes all annotated?

**Comment by disovi** [comment]
Can you give ids of those users? We can remove those annotations, this is just legacy)

**Comment by dan-s1** [comment]
I am sorry I tried the user again and I am noticing the instagram entry. I am not sure what made me think it wasn't there.

**Comment by dan-s1** [comment]
But somewhat related is for user with 7019889 I notice on his page he has connections for Skype, Instagram, Twitter, Facebook and LiveJournal yet the API when I curl from the command line 
curl "https://api.vk.com/method/users.get?v=5.27&user_ids=7019889&fields=connections" it returns all of these connections except for Skype. Would you know why this is the case?

**Comment by disovi** [comment]
It looks like a vk bug.

**Comment by vkolodrevskiy** [comment]
Since library depends on VK API SDK closing this. Refer to SDK.
