### ISSUE TITLE
org.springframework.social.vkontakte.api.IWallOperations does not expose filter to filter on type of posts to return

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#46]
Per http://vk.com/dev/wall.get the Wall API has a filter field which allows to get posts by owner, others, all (the default) and postponed.  The org.springframework.social.vkontakte.api.IWallOperations does not expose this.

**Comment by dan-s1** [comment]
The filter also has a suggests value

**Comment by dan-s1** [comment]
I just tested using the current Spring Social API and trying filtering out only owner posts and I got 93 out of a 100 messages yet when I use the VK API straight with the owner filter I got the last 100 messages from the owner. It would be great to be able to get the desired type of post since one can get more in one call (as seen from above test).

**Comment by vkolodrevskiy** [comment]
Since library depends on VK API SDK closing this. Refer to SDK.
