### ISSUE TITLE
org.springframework.social.vkontakte.api.IUsersOperations does not expose a method to retrieve a users followers

### ISSUE THREAD

**Issue by dan-s1** [vkolodrevskiy/spring-social-vkontakte#47]
Per the VK API http://vk.com/dev/users.getFollowers there is a method to get a user's followers.
The org.springframework.social.vkontakte.api.IUsersOperations interface which mirrors the users api has no method which allows for obtaining a user's followers. Can this please be added? Thanks!

**Comment by vkolodrevskiy** [comment]
Since library depends on VK API SDK closing this. Refer to SDK.
