### ISSUE TITLE
friends.get requires authorization but it shouldn't

### ISSUE THREAD

**Issue by saladinkzn** [vkolodrevskiy/spring-social-vkontakte#54]
I'm trying to get user's friends by id but I get MissingAuthorizationException

Method:
org.springframework.social.vkontakte.api.IFriendsOperations#get(java.lang.Long)

But as far as I can see in doc:
https://vk.com/dev/friends.get

this method does not require access token to be sent (it works in browser btw)

**Comment by vkolodrevskiy** [comment]
Since in 2.0.0 spring-social-vkontakte is using internally VK Java SDK as client API implementation, please refer to it's doc how to do it.
