### ISSUE TITLE
Private messages support

### ISSUE THREAD

**Issue by roman-voropaev** [vkolodrevskiy/spring-social-vkontakte#57]
I'm developing a webapp for communication between different social networks. 
And I really need some standard way for *sending/receiving messages* in VK (and that's possible for **Standalone** applications - https://vk.com/dev/messages.get). 
Is it planned to support this functionality in _spring-social-vkontakte_? Thnx.

**Comment by vkolodrevskiy** [comment]
As you already said, this API is available only for standalone apps. spring-social-vkontakte is for websites, so it will not support this API.
