### ISSUE TITLE
fugru.com server is down

### ISSUE THREAD

**Issue by alexanderantonov** [vkolodrevskiy/spring-social-vkontakte#59]
Not sure if it is a right place for the issue, but fugru.com server is down for several days. Our project depends on the fugru.com maven repository and doesn't build now. Please let me know if you are going to restore the server, or where else can I get "spring-social-vkontakte 1.1.0.BUILD-SNAPSHOT"? TIA.

**Comment by vkolodrevskiy** [comment]
Hi @alexanderantonov,
Looks like tomcat crashed, I've restarted and it should be working now.
Thanks for posting.
